-- ============================================
-- Hify MCP 模块数据库设计（H2 兼容版本）
-- ============================================

CREATE TABLE IF NOT EXISTS t_mcp_server (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(64)     NOT NULL,
    endpoint        VARCHAR(255)    NOT NULL,
    enabled         INT         NOT NULL DEFAULT 1,
    status          VARCHAR(16)     NOT NULL DEFAULT 'unknown',
    tool_count      INT             NOT NULL DEFAULT 0,
    last_check_time TIMESTAMP,
    last_error_msg  VARCHAR(512),

    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         INT         NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_name_deleted ON t_mcp_server(name, deleted);
CREATE INDEX IF NOT EXISTS idx_status_deleted ON t_mcp_server(status, deleted);

CREATE TABLE IF NOT EXISTS t_mcp_tool (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id       BIGINT          NOT NULL,
    name            VARCHAR(64)     NOT NULL,
    description     VARCHAR(500),
    input_schema    TEXT,

    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         INT         NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_server_tool_deleted ON t_mcp_tool(server_id, name, deleted);
CREATE INDEX IF NOT EXISTS idx_server_id ON t_mcp_tool(server_id, deleted);
