-- ============================================
-- Hify Agent 模块数据库设计（H2 兼容版本）
-- ============================================

CREATE TABLE IF NOT EXISTS t_agent (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(100)    NOT NULL,
    description         VARCHAR(500)    NOT NULL DEFAULT '',
    system_prompt       TEXT,
    model_config_id     BIGINT          NOT NULL,
    knowledge_base_id   BIGINT,
    temperature         DECIMAL(3,2)    NOT NULL DEFAULT 0.70,
    max_tokens          INT             NOT NULL DEFAULT 2048,
    max_context_turns   INT             NOT NULL DEFAULT 10,
    enabled             INT         NOT NULL DEFAULT 1,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted             INT         NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_name_deleted ON t_agent(name, deleted);
CREATE INDEX IF NOT EXISTS idx_model_config ON t_agent(model_config_id, deleted);
CREATE INDEX IF NOT EXISTS idx_knowledge_base ON t_agent(knowledge_base_id, deleted);

CREATE TABLE IF NOT EXISTS t_agent_tool (
    id            BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id      BIGINT          NOT NULL,
    tool_id       BIGINT          NOT NULL COMMENT '关联工具 ID（t_mcp_tool.id）',
    created_at    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_agent_tool ON t_agent_tool(agent_id, tool_id);
CREATE INDEX IF NOT EXISTS idx_agent_tool_agent_id ON t_agent_tool(agent_id);

CREATE TABLE IF NOT EXISTS t_agent_knowledge_rel (
    id            BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id      BIGINT          NOT NULL,
    knowledge_id  BIGINT          NOT NULL,
    created_at    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_agent_knowledge ON t_agent_knowledge_rel(agent_id, knowledge_id);
CREATE INDEX IF NOT EXISTS idx_agent_knowledge_agent_id ON t_agent_knowledge_rel(agent_id);
-- ============================================
-- Hify Chat 模块数据库设计（H2 兼容版本）
-- ============================================

CREATE TABLE IF NOT EXISTS t_chat_session (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id    BIGINT          NOT NULL,
    title       VARCHAR(200)    NOT NULL DEFAULT '',
    user_id     BIGINT,
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     INT         NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_chat_session_agent ON t_chat_session(agent_id, deleted);
CREATE INDEX IF NOT EXISTS idx_chat_session_created ON t_chat_session(created_at, deleted);

CREATE TABLE IF NOT EXISTS t_chat_message (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT          NOT NULL,
    role        VARCHAR(20)     NOT NULL,
    content     TEXT            NOT NULL,
    tokens      INT,
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     INT         NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_chat_message_session ON t_chat_message(session_id, deleted, created_at);
-- ============================================
-- Hify MCP 模块数据库设计（H2 兼容版本）
-- ============================================

CREATE TABLE IF NOT EXISTS t_mcp_server (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(64)     NOT NULL,
    endpoint        VARCHAR(255)    NOT NULL,
    enabled         INT         NOT NULL DEFAULT 1,
    status          VARCHAR(16)     NOT NULL DEFAULT 'unknown',
    tool_count      INT             NOT NULL DEFAULT 0,
    last_check_time TIMESTAMP,
    last_error_msg  VARCHAR(512),

    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         INT         NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_name_deleted ON t_mcp_server(name, deleted);
CREATE INDEX IF NOT EXISTS idx_status_deleted ON t_mcp_server(status, deleted);

CREATE TABLE IF NOT EXISTS t_mcp_tool (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id       BIGINT          NOT NULL,
    name            VARCHAR(64)     NOT NULL,
    description     VARCHAR(500),
    input_schema    TEXT,

    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         INT         NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_server_tool_deleted ON t_mcp_tool(server_id, name, deleted);
CREATE INDEX IF NOT EXISTS idx_server_id ON t_mcp_tool(server_id, deleted);
-- ============================================
-- Hify Provider 模块数据库设计（H2 兼容版本）
-- ============================================

CREATE TABLE IF NOT EXISTS t_provider (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(32)     NOT NULL,
    name                VARCHAR(64)     NOT NULL,
    provider_type       VARCHAR(32)     NOT NULL,
    base_url            VARCHAR(255)    NOT NULL,
    auth_type           VARCHAR(16)     NOT NULL DEFAULT 'bearer',
    api_key             VARCHAR(512),
    auth_config         TEXT,
    timeout_ms          INT             NOT NULL DEFAULT 90000,
    max_retries         INT             NOT NULL DEFAULT 3,
    status              VARCHAR(16)     NOT NULL DEFAULT 'active',
    health_status       VARCHAR(16)     NOT NULL DEFAULT 'unknown',
    consecutive_failures INT            NOT NULL DEFAULT 0,
    last_check_time     TIMESTAMP,
    last_error_msg      VARCHAR(512),
    fallback_provider_id BIGINT,
    sort_order          INT             NOT NULL DEFAULT 0,
    remark              VARCHAR(255),
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted             INT         NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_code_deleted ON t_provider(code, deleted);
CREATE INDEX IF NOT EXISTS idx_type_status ON t_provider(provider_type, deleted, status);
CREATE INDEX IF NOT EXISTS idx_health_status ON t_provider(health_status, deleted);

CREATE TABLE IF NOT EXISTS t_model (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id         BIGINT          NOT NULL,
    model_code          VARCHAR(64)     NOT NULL,
    model_name          VARCHAR(64)     NOT NULL,
    model_type          VARCHAR(16)     NOT NULL DEFAULT 'chat',
    max_context_tokens  INT,
    max_output_tokens   INT,
    supports_streaming  INT         NOT NULL DEFAULT 1,
    supports_tool_calls INT         NOT NULL DEFAULT 0,
    supports_vision     INT         NOT NULL DEFAULT 0,
    supports_json_mode  INT         NOT NULL DEFAULT 0,
    input_price         BIGINT,
    output_price        BIGINT,
    extra_params        TEXT,
    status              VARCHAR(16)     NOT NULL DEFAULT 'active',
    is_default          INT         NOT NULL DEFAULT 0,
    sort_order          INT             NOT NULL DEFAULT 0,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted             INT         NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_provider_model_deleted ON t_model(provider_id, model_code, deleted);
CREATE INDEX IF NOT EXISTS idx_provider_status ON t_model(provider_id, deleted, status);
CREATE INDEX IF NOT EXISTS idx_model_type ON t_model(model_type, deleted);

CREATE TABLE IF NOT EXISTS t_provider_health (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id         BIGINT          NOT NULL,
    health_status       VARCHAR(16)     NOT NULL DEFAULT 'unknown',
    consecutive_failures INT            NOT NULL DEFAULT 0,
    last_check_time     TIMESTAMP,
    last_error_msg      VARCHAR(512),
    response_time_ms    BIGINT,
    UNIQUE (provider_id)
);
