-- ============================================
-- Knowledge 模块集成测试预置数据
-- ============================================

-- t_knowledge_base 表（H2 兼容，无 pgvector）
CREATE TABLE IF NOT EXISTS t_knowledge_base (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)    NOT NULL,
    description VARCHAR(500)    NOT NULL DEFAULT '',
    enabled     INT             NOT NULL DEFAULT 1,
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     INT             NOT NULL DEFAULT 0
);

-- t_document 表（H2 兼容）
CREATE TABLE IF NOT EXISTS t_document (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id BIGINT NOT NULL,
    name            VARCHAR(255)    NOT NULL,
    file_type       VARCHAR(16)     NOT NULL,
    file_size       BIGINT          NOT NULL DEFAULT 0,
    status          VARCHAR(16)     NOT NULL DEFAULT 'PENDING',
    error_message   VARCHAR(512),
    chunk_count     INT             NOT NULL DEFAULT 0,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         INT             NOT NULL DEFAULT 0
);

-- document_chunk 表（用于 H2 测试，不使用 pgvector 向量类型）
CREATE TABLE IF NOT EXISTS document_chunk (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id BIGINT NOT NULL,
    document_id     BIGINT NOT NULL,
    chunk_index     INT NOT NULL,
    content         TEXT NOT NULL,
    embedding       VARCHAR(1024),
    token_count     INT DEFAULT 0,
    deleted         INT DEFAULT 0,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 清理旧数据（使脚本可重复执行）
DELETE FROM document_chunk WHERE document_id IN (SELECT id FROM t_document WHERE knowledge_base_id = 500);
DELETE FROM t_document WHERE knowledge_base_id = 500;
DELETE FROM t_chat_session WHERE id = 500;
DELETE FROM t_agent WHERE id = 500;
DELETE FROM t_model WHERE id = 500;
DELETE FROM t_provider WHERE id IN (500, 1);
DELETE FROM t_knowledge_base WHERE id = 500;

-- 知识库
INSERT INTO t_knowledge_base (id, name, description, enabled, deleted, created_at, updated_at)
VALUES (500, 'Test KB', '测试知识库', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 文档 1: PENDING 状态
INSERT INTO t_document (id, knowledge_base_id, name, file_type, file_size, status, chunk_count, deleted, created_at, updated_at)
VALUES (501, 500, 'test1.pdf', 'pdf', 10240, 'PENDING', 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 文档 2: DONE 状态
INSERT INTO t_document (id, knowledge_base_id, name, file_type, file_size, status, chunk_count, deleted, created_at, updated_at)
VALUES (502, 500, 'test2.txt', 'txt', 2048, 'DONE', 3, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 文档 3: FAILED 状态
INSERT INTO t_document (id, knowledge_base_id, name, file_type, file_size, status, chunk_count, deleted, created_at, updated_at)
VALUES (503, 500, 'test3.pdf', 'pdf', 51200, 'FAILED', 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- chunks for doc 502
INSERT INTO document_chunk (id, document_id, knowledge_base_id, content, chunk_index, token_count, deleted, created_at, updated_at)
VALUES
(511, 502, 500, 'Chunk 1 content about AI', 0, 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(512, 502, 500, 'Chunk 2 content about ML', 1, 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(513, 502, 500, 'Chunk 3 content about NLP', 2, 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Provider + Model + Agent 绑定知识库（用于 RAG 测试）
INSERT INTO t_provider (id, code, name, provider_type, base_url, auth_type, status, timeout_ms, max_retries, sort_order, deleted)
VALUES (500, 'kb-provider', 'KB Provider', 'openai_compatible', 'https://api.kb.com', 'bearer', 'active', 90000, 3, 0, 0);

INSERT INTO t_model (id, provider_id, model_code, model_name, model_type, status, sort_order, deleted)
VALUES (500, 500, 'gpt-4', 'GPT-4', 'chat', 'active', 0, 0);

INSERT INTO t_agent (id, name, model_config_id, knowledge_base_id, temperature, max_tokens, max_context_turns, enabled, deleted)
VALUES (500, 'KB Agent', 500, 500, 0.70, 2048, 10, 1, 0);

-- Chat session for RAG test
INSERT INTO t_chat_session (id, agent_id, title, deleted)
VALUES (500, 500, 'KB Test Session', 0);
