-- ============================================
-- Workflow 模块表结构（仅 CREATE TABLE，无数据）
-- ============================================

CREATE TABLE IF NOT EXISTS t_workflow (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(100)    NOT NULL,
    description         VARCHAR(500)    NOT NULL DEFAULT '',
    enabled             INT             NOT NULL DEFAULT 1,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted             INT             NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS t_workflow_node (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id         BIGINT          NOT NULL,
    node_key            VARCHAR(50)     NOT NULL,
    node_type           VARCHAR(20)     NOT NULL,
    name                VARCHAR(100)    NOT NULL DEFAULT '',
    config_json         CLOB            NOT NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted             INT             NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS t_workflow_edge (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id         BIGINT          NOT NULL,
    source_node_key     VARCHAR(50)     NOT NULL,
    target_node_key     VARCHAR(50)     NOT NULL,
    condition_expr      VARCHAR(500)    NOT NULL DEFAULT '',
    sort_order          INT             NOT NULL DEFAULT 0,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted             INT             NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS t_workflow_run (
    id           BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id  BIGINT          NOT NULL,
    status       VARCHAR(20)     NOT NULL,
    input        CLOB,
    output       CLOB,
    error        VARCHAR(500)    NOT NULL DEFAULT '',
    elapsed_ms   INT,
    created_at   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted      INT             NOT NULL DEFAULT 0,
    finished_at  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_workflow_node_run (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_run_id BIGINT          NOT NULL,
    node_key        VARCHAR(64)     NOT NULL,
    node_type       VARCHAR(30)     NOT NULL,
    status          VARCHAR(20)     NOT NULL,
    outputs         CLOB,
    error           VARCHAR(500)    NOT NULL DEFAULT '',
    elapsed_ms      INT,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         INT             NOT NULL DEFAULT 0,
    finished_at     TIMESTAMP
);
